# Generated by Django 2.0.7 on 2018-10-12 02:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app_connection', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_name', models.CharField(max_length=50, unique=True)),
                ('class_name', models.CharField(blank=True, max_length=50)),
                ('query_sql', models.CharField(max_length=300)),
                ('links', models.CharField(blank=True, max_length=300)),
                ('roles', models.CharField(blank=True, max_length=100)),
                ('connection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_connection.Connection')),
            ],
            options={
                'verbose_name': 'Service',
                'verbose_name_plural': 'Services',
            },
        ),
    ]
