# Generated by Django 2.1.3 on 2018-11-08 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_services', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='service',
            field=models.ForeignKey(limit_choices_to={'kind': 'map'}, on_delete='CASCADE', related_name='locations', related_query_name='location', to='app_services.Service'),
        ),
        migrations.AlterField(
            model_name='missingitem',
            name='service',
            field=models.ForeignKey(limit_choices_to={'kind': 'catalog'}, on_delete='CASCADE', related_name='items', related_query_name='item', to='app_services.Service'),
        ),
        migrations.AlterField(
            model_name='office',
            name='service',
            field=models.ForeignKey(limit_choices_to={'kind': 'directory'}, on_delete='CASCADE', related_name='offices', related_query_name='office', to='app_services.Service'),
        ),
        migrations.AlterField(
            model_name='sqlquery',
            name='service',
            field=models.OneToOneField(limit_choices_to={'kind': 'query'}, on_delete='CASCADE', primary_key=True, related_name='query', related_query_name='query', serialize=False, to='app_services.Service'),
        ),
    ]
