# Generated by Django 2.1.3 on 2018-11-02 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_services', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='description',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='location',
            name='icon',
            field=models.ForeignKey(blank=True, default=None, on_delete='PROTECTED', to='app_services.Icon'),
        ),
        migrations.AlterField(
            model_name='service',
            name='icon',
            field=models.ForeignKey(on_delete='PROTECTED', to='app_services.Icon'),
        ),
        migrations.AlterField(
            model_name='service',
            name='permits',
            field=models.ForeignKey(on_delete='PROTECTED', to='app_services.Permits'),
        ),
    ]
