# Generated by Django 2.0.7 on 2018-10-12 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_services', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='unique_key',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
