# Generated by Django 2.0.7 on 2018-11-04 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_services', '0002_auto_20181102_0453'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='service',
            field=models.ForeignKey(limit_choices_to={'kind': 'map'}, on_delete='CASCADE', related_name='locations', related_query_name='location', to='app_services.Service'),
        ),
        migrations.AlterField(
            model_name='missingitem',
            name='service',
            field=models.ForeignKey(limit_choices_to={'kind': 'catalog'}, on_delete='CASCADE', related_name='items', related_query_name='item', to='app_services.Service'),
        ),
    ]
