# Generated by Django 2.0.7 on 2018-10-13 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_services', '0002_service_unique_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='class_name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
