# Generated by Django 2.0.7 on 2018-10-15 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_services', '0003_auto_20181013_2350'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='icon',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
