# Generated by Django 2.0.7 on 2018-10-15 15:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_services', '0004_service_icon'),
    ]

    operations = [
        migrations.RenameField(
            model_name='service',
            old_name='class_name',
            new_name='type_name',
        ),
    ]
