# Generated by Django 2.0.7 on 2018-10-15 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_services', '0005_auto_20181015_1556'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='description_fields',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
