# Generated by Django 2.0.7 on 2018-10-29 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_services', '0006_service_description_fields'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='service',
            options={},
        ),
        migrations.RemoveField(
            model_name='service',
            name='connection',
        ),
        migrations.RemoveField(
            model_name='service',
            name='description_fields',
        ),
        migrations.RemoveField(
            model_name='service',
            name='icon',
        ),
        migrations.RemoveField(
            model_name='service',
            name='links',
        ),
        migrations.RemoveField(
            model_name='service',
            name='query_sql',
        ),
        migrations.RemoveField(
            model_name='service',
            name='roles',
        ),
        migrations.RemoveField(
            model_name='service',
            name='service_name',
        ),
        migrations.RemoveField(
            model_name='service',
            name='type_name',
        ),
        migrations.RemoveField(
            model_name='service',
            name='unique_key',
        ),
        migrations.AddField(
            model_name='service',
            name='permits',
            field=models.IntegerField(default=0),
        ),
    ]
