# Generated by Django 2.0.7 on 2018-10-29 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_services', '0008_auto_20181029_1911'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='kind',
            field=models.CharField(choices=[('sqlquery', 'Consulta SQL'), ('item', 'Objetos Perdidos'), ('directory', 'Directorio de Dependencias'), ('localization', 'Geolocalizacion de Bloques')], max_length=20),
        ),
        migrations.AlterField(
            model_name='service',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='permits',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='service',
            name='state',
            field=models.BooleanField(),
        ),
    ]
