# Generated by Django 2.0.7 on 2018-10-31 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_services', '0009_auto_20181029_1913'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sqlquery',
            options={'verbose_name': 'Query', 'verbose_name_plural': 'Queries'},
        ),
        migrations.RemoveField(
            model_name='service',
            name='links',
        ),
        migrations.RemoveField(
            model_name='service',
            name='permits',
        ),
    ]
