# Generated by Django 2.0.7 on 2018-10-31 19:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_services', '0010_auto_20181031_1417'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='unique_key',
        ),
    ]
