# Generated by Django 2.1.3 on 2018-11-08 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_services', '0001_initial'),
        ('app_admin', '0003_auto_20181106_0233'),
    ]

    operations = [
        migrations.AddField(
            model_name='rol',
            name='groups',
            field=models.ManyToManyField(to='app_services.Group'),
        ),
    ]
