# Generated by Django 2.0.5 on 2018-05-21 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0002_remove_connection_dbname2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='connection',
            name='manager_db',
            field=models.CharField(choices=[('myslq', 'MySQL'), ('postgresql', 'postgreSQL'), ('oracle', 'Oracle')], max_length=50),
        ),
    ]
