# Generated by Django 2.0.5 on 2018-05-26 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0003_auto_20180521_2128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='connection',
            name='manager_db',
            field=models.CharField(choices=[('mysql', 'MySQL'), ('postgresql', 'postgreSQL'), ('oracle', 'Oracle')], max_length=50),
        ),
    ]
