# Generated by Django 2.0.5 on 2018-06-09 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0004_auto_20180526_2114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='connection',
            name='connection_name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
