# Generated by Django 2.0.6 on 2018-07-12 15:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0005_auto_20180609_1050'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_name', models.CharField(max_length=50)),
                ('query_sql', models.CharField(max_length=300)),
                ('connection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminapp.Connection')),
            ],
            options={
                'verbose_name': 'Service',
                'verbose_name_plural': 'Services',
            },
        ),
    ]
