# Generated by Django 2.0.7 on 2018-07-30 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0007_auto_20180712_2255'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='class_name',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
