# Generated by Django 2.0.7 on 2018-09-13 20:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0013_auto_20180912_2209'),
    ]

    operations = [
        migrations.RenameField(
            model_name='service',
            old_name='relationships',
            new_name='links',
        ),
    ]
