# Generated by Django 2.0.7 on 2018-10-08 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Connection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('connection_name', models.CharField(max_length=50, unique=True)),
                ('host', models.CharField(max_length=16)),
                ('port', models.IntegerField()),
                ('manager_db', models.CharField(choices=[('mysql', 'MySQL'), ('postgresql', 'postgreSQL'), ('oracle', 'Oracle')], max_length=50)),
                ('user', models.CharField(max_length=50)),
                ('passwd', models.CharField(blank=True, max_length=50)),
                ('dbname', models.CharField(max_length=50)),
            ],
        ),
    ]
